---
- name: Download Composer
  ansible.builtin.shell: curl -sS https://getcomposer.org/installer | php

- name: Install Composer
  ansible.builtin.copy:
    dest: /usr/local/bin/composer
    mode: 0755
    remote_src: true
    src: /root/composer.phar

- name: Clean Composer Installation Files
  ansible.builtin.file:
    path: /root/composer.phar
    state: absent
